/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal_p2_jorgerush;

import javax.swing.DefaultComboBoxModel;
import javax.swing.UIManager;
import java.awt.Color;

/**
 *
 * @author Jorge Rush
 */
public class Default extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Default.class.getName());

    /**
     * Creates new form Default
     */
    public Default() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BarraNavegacion = new javax.swing.JPanel();
        explorarArchivos = new javax.swing.JButton();
        editarPantalla = new javax.swing.JButton();
        editorTexto = new javax.swing.JButton();
        WitZig = new javax.swing.JButton();
        FondoPantalla = new javax.swing.JPanel();
        editor = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        Color = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        buscador = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraNavegacion.setBackground(new java.awt.Color(209, 209, 209));
        BarraNavegacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        explorarArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ExploradorArchivos-removebg-preview (2).png"))); // NOI18N
        explorarArchivos.setContentAreaFilled(false);
        explorarArchivos.setFocusPainted(false);
        explorarArchivos.addActionListener(this::explorarArchivosActionPerformed);
        BarraNavegacion.add(explorarArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 40, -1));

        editarPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sprite-frame-21 (2).png"))); // NOI18N
        editarPantalla.setBorderPainted(false);
        editarPantalla.setContentAreaFilled(false);
        editarPantalla.setFocusPainted(false);
        editarPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarPantallaMouseClicked(evt);
            }
        });
        editarPantalla.addActionListener(this::editarPantallaActionPerformed);
        BarraNavegacion.add(editarPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 40, -1));

        editorTexto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/EditorTexto-removebg-preview (2) (2).png"))); // NOI18N
        editorTexto.setContentAreaFilled(false);
        editorTexto.setFocusPainted(false);
        BarraNavegacion.add(editorTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 40, -1));

        WitZig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipoWitzig (2).png"))); // NOI18N
        WitZig.setBorder(null);
        WitZig.setBorderPainted(false);
        WitZig.setFocusPainted(false);
        BarraNavegacion.add(WitZig, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        jPanel1.add(BarraNavegacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 481));

        FondoPantalla.setBackground(new java.awt.Color(255, 255, 255));
        FondoPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Color.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(380, Short.MAX_VALUE)
                .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(Color, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        editor.addTab("Editor de Fuente", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 295, Short.MAX_VALUE)
        );

        editor.addTab("Personalizacion de fondo", jPanel5);

        FondoPantalla.add(editor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 490, 330));

        buscador.setForeground(new java.awt.Color(153, 153, 153));
        buscador.setText("Buscar..");
        buscador.setCaretColor(new java.awt.Color(102, 102, 102));
        buscador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        buscador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buscadorMouseClicked(evt);
            }
        });
        buscador.addActionListener(this::buscadorActionPerformed);
        FondoPantalla.add(buscador, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("WitZig");
        FondoPantalla.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 60, 30));

        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 750, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscadorActionPerformed

    }//GEN-LAST:event_buscadorActionPerformed

    private void buscadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscadorMouseClicked
        buscador.setText(null);
    }//GEN-LAST:event_buscadorMouseClicked

    private void editarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarPantallaActionPerformed

    private void editarPantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarPantallaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_editarPantallaMouseClicked

    private void explorarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorarArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_explorarArchivosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Default().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraNavegacion;
    private javax.swing.JComboBox<String> Color;
    private javax.swing.JPanel FondoPantalla;
    private javax.swing.JButton WitZig;
    private javax.swing.JTextField buscador;
    private javax.swing.JButton editarPantalla;
    private javax.swing.JTabbedPane editor;
    private javax.swing.JButton editorTexto;
    private javax.swing.JButton explorarArchivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
