/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectofinal_p2_jorgerush;

import java.awt.Color;
import java.io.File;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Rush
 */
public class ExploradorDeArchivos extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExploradorDeArchivos.class.getName());

    /**
     * Creates new form ExploradorDeArchivos
     */
    ArrayList<carpetasArchivos> carpetasCreadas = new ArrayList<>();

    public ExploradorDeArchivos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
//        crear.setVisible(false);
        DefaultTableModel modeloTabla = new DefaultTableModel();
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Fecha de Modificacion");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Tamaño");
        tablaArchivos.setModel(modeloTabla);
        panelArchivo.setVisible(false);
        botonCrear.setVisible(false);
    }

    public void cargarArchivos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.JPopupMenu();
        nuevo = new javax.swing.JMenu();
        crearCarpeta = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buscarArchivo = new javax.swing.JTextField();
        fondoArchivos = new javax.swing.JPanel();
        carpetas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();
        panelArchivo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArchivos1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        nombreArchivo = new javax.swing.JTextField();
        botonGuardar = new javax.swing.JButton();
        botonCrear = new javax.swing.JButton();
        tipoArchivo = new javax.swing.JComboBox<>();

        nuevo.setText("Nuevo");

        crearCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/C1.png"))); // NOI18N
        crearCarpeta.setText("Crear Carpeta");
        crearCarpeta.addActionListener(this::crearCarpetaActionPerformed);
        nuevo.add(crearCarpeta);

        opciones.add(nuevo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 439));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setText("jTextField1");
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 460, -1));

        jButton1.setText("<");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 40));

        buscarArchivo.setText("jTextField1");
        getContentPane().add(buscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 6, 446, -1));

        fondoArchivos.setBackground(new java.awt.Color(255, 255, 255));
        fondoArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoArchivosMouseClicked(evt);
            }
        });
        fondoArchivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carpetas.setBackground(new java.awt.Color(255, 255, 255));
        carpetas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaArchivos);

        carpetas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 508, 210));

        fondoArchivos.add(carpetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 210));

        panelArchivo.setBackground(new java.awt.Color(255, 255, 255));
        panelArchivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaArchivos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaArchivos1);

        panelArchivo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 508, 210));

        fondoArchivos.add(panelArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 210));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreArchivo.setForeground(new java.awt.Color(153, 153, 153));
        nombreArchivo.setText("Ingrese nombre de la carpeta");
        nombreArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreArchivoMouseClicked(evt);
            }
        });
        jPanel4.add(nombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        botonGuardar.setText("Guardar");
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });
        jPanel4.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        botonCrear.setText("Crear");
        botonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearMouseClicked(evt);
            }
        });
        jPanel4.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        tipoArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carpeta de Archivos", ".txt" }));
        jPanel4.add(tipoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 140, -1));

        fondoArchivos.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 510, 40));

        getContentPane().add(fondoArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 590, 340));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMouseClicked
//       Principal framePrincipal = (Principal) getParent();
//        String nombre = framePrincipal.editorTexto.llamarHoja().getText();
       botonCrear.setVisible(true);
        String tipoArch = (String) tipoArchivo.getSelectedItem();
        if (tipoArch.equals("Carpeta de Archivos")) {
            String nombre = nombreArchivo.getText();
            String fecha = LocalDate.now().toString();
            String tipo = tipoArch;
            carpetasArchivos nuevaCarpeta = new carpetasArchivos(nombre, fecha, tipo);
            carpetasCreadas.add(nuevaCarpeta);
            String[] Datos = {nuevaCarpeta.nombre, nuevaCarpeta.fechaMod, nuevaCarpeta.tipo, "   " + nuevaCarpeta.tamaño + "  "};
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaArchivos.getModel();
            modeloTabla.addRow(Datos);

        }else{
            JOptionPane.showMessageDialog(this,"El tipo de Archivo no es una carpeta.");
        }


    }//GEN-LAST:event_botonCrearMouseClicked

    private void crearCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCarpetaActionPerformed
        botonCrear.setText("Crear");
   
    }//GEN-LAST:event_crearCarpetaActionPerformed

    private void fondoArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoArchivosMouseClicked
        int boton = evt.getButton();
        if (boton == 1) {

        } else if (boton == 3) {
            int x = evt.getX();
            int y = evt.getY();
            opciones.show(fondoArchivos, x, y);
        }
    }//GEN-LAST:event_fondoArchivosMouseClicked

    private void nombreArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreArchivoMouseClicked
        nombreArchivo.setText(null);
        nombreArchivo.setForeground(Color.BLACK);
    }//GEN-LAST:event_nombreArchivoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Principal framePrincipal = (Principal) getParent();
        if (framePrincipal.editorTexto.verificarGuardado()==true){
            
        }
    }//GEN-LAST:event_formWindowOpened

    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_botonGuardarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ExploradorDeArchivos dialog = new ExploradorDeArchivos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField buscarArchivo;
    private javax.swing.JPanel carpetas;
    private javax.swing.JMenuItem crearCarpeta;
    private javax.swing.JPanel fondoArchivos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JMenu nuevo;
    private javax.swing.JPopupMenu opciones;
    private javax.swing.JPanel panelArchivo;
    private javax.swing.JTable tablaArchivos;
    private javax.swing.JTable tablaArchivos1;
    private javax.swing.JComboBox<String> tipoArchivo;
    // End of variables declaration//GEN-END:variables
}
