/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectofinal_p2_jorgerush;

import java.awt.Color;
import java.io.File;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jorge Rush
 */
public class ExploradorDeArchivos extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExploradorDeArchivos.class.getName());

    /**
     * Creates new form ExploradorDeArchivos
     */
    ArrayList<carpetasArchivos> carpetasCreadas = new ArrayList<>();

    public ExploradorDeArchivos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        DefaultTableModel modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        DefaultTableModel modeloTablaArchivos = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Fecha de Modificacion");
        modeloTabla.addColumn("Tipo");
        modeloTabla.addColumn("Tamaño");
        modeloTablaArchivos.addColumn("Nombre");
        modeloTablaArchivos.addColumn("Fecha de Modificacion");
        modeloTablaArchivos.addColumn("Tipo");
        modeloTablaArchivos.addColumn("Tamaño");

        botonCrear.setVisible(false);
        botonGuardar.setVisible(false);

        tablaArchivos.setModel(modeloTabla);
        tablaContenidoArchivos.setModel(modeloTablaArchivos);
        tablaContenidoArchivos.setVisible(false);

        panelArchivo.setVisible(false);
        panelArchivos.setVisible(false);

    }

    public void cargarArchivos() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opciones = new javax.swing.JPopupMenu();
        nuevo = new javax.swing.JMenu();
        crearCarpeta = new javax.swing.JMenuItem();
        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        ruta = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        buscarArchivo = new javax.swing.JTextField();
        fondoArchivos = new javax.swing.JPanel();
        carpetas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();
        panelArchivo = new javax.swing.JPanel();
        tablaContenido = new javax.swing.JScrollPane();
        tablaContenidoArchivos = new javax.swing.JTable();
        panelArchivos = new javax.swing.JPanel();
        nombreArchivo = new javax.swing.JTextField();
        botonCrear = new javax.swing.JButton();
        tipoArchivo = new javax.swing.JComboBox<>();
        botonGuardar = new javax.swing.JButton();

        nuevo.setText("Nuevo");

        crearCarpeta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/C1.png"))); // NOI18N
        crearCarpeta.setText("Crear Carpeta");
        crearCarpeta.addActionListener(this::crearCarpetaActionPerformed);
        nuevo.add(crearCarpeta);

        opciones.add(nuevo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(612, 360));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(580, 360));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ruta.setText("jTextField1");
        ruta.addActionListener(this::rutaActionPerformed);
        jPanel1.add(ruta, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 530, -1));

        jButton1.setText("<");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        buscarArchivo.setText("jTextField1");
        getContentPane().add(buscarArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 6, 446, -1));

        fondoArchivos.setBackground(new java.awt.Color(255, 255, 255));
        fondoArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoArchivosMouseClicked(evt);
            }
        });
        fondoArchivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        carpetas.setBackground(new java.awt.Color(255, 255, 255));
        carpetas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaArchivosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaArchivos);

        carpetas.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 210));

        fondoArchivos.add(carpetas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 210));

        panelArchivo.setBackground(new java.awt.Color(255, 255, 255));
        panelArchivo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaContenidoArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaContenidoArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaContenidoArchivosMouseClicked(evt);
            }
        });
        tablaContenido.setViewportView(tablaContenidoArchivos);

        panelArchivo.add(tablaContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 210));

        fondoArchivos.add(panelArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 560, 210));

        panelArchivos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nombreArchivo.setForeground(new java.awt.Color(153, 153, 153));
        nombreArchivo.setText("Ingrese nombre de la carpeta");
        nombreArchivo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nombreArchivoMouseClicked(evt);
            }
        });
        panelArchivos.add(nombreArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        botonCrear.setText("Crear");
        botonCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonCrearMouseClicked(evt);
            }
        });
        panelArchivos.add(botonCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        tipoArchivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Carpeta de Archivos", ".txt" }));
        panelArchivos.add(tipoArchivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 140, -1));

        botonGuardar.setText("Guardar");
        botonGuardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botonGuardarMouseClicked(evt);
            }
        });
        panelArchivos.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        fondoArchivos.add(panelArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 480, 40));

        getContentPane().add(fondoArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 600, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCrearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonCrearMouseClicked
//       Principal framePrincipal = (Principal) getParent();
//        String nombre = framePrincipal.editorTexto.llamarHoja().getText();
        String tipoArch = (String) tipoArchivo.getSelectedItem();

        if (tipoArch.equals("Carpeta de Archivos")) {
            String nombre = nombreArchivo.getText();
            if (nombre.isEmpty() || nombre.equals("Ingrese nombre de la carpeta")) {
                JOptionPane.showMessageDialog(this, "Debe elegir un nombre para la carpeta.");
                return;
            }
            String fecha = LocalDate.now().toString();
            String tipo = tipoArch;
            carpetasArchivos nuevaCarpeta = new carpetasArchivos(nombre, fecha, tipo);
            carpetasCreadas.add(nuevaCarpeta);
            String[] Datos = {nuevaCarpeta.nombre, nuevaCarpeta.fechaMod, nuevaCarpeta.tipo, "   " + nuevaCarpeta.tamaño + "  "};
            DefaultTableModel modeloTabla = (DefaultTableModel) tablaArchivos.getModel();
            modeloTabla.addRow(Datos);
            panelArchivos.setVisible(false);

        } else {
            JOptionPane.showMessageDialog(this, "El tipo de Archivo no es una carpeta.");
        }


    }//GEN-LAST:event_botonCrearMouseClicked

    private void crearCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCarpetaActionPerformed
        panelArchivos.setVisible(true);
        botonCrear.setVisible(true);
        botonGuardar.setVisible(false);
        nombreArchivo.setText("Ingrese nombre de la carpeta.");

    }//GEN-LAST:event_crearCarpetaActionPerformed

    private void fondoArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoArchivosMouseClicked
        int boton = evt.getButton();
        if (boton == 1) {

        } else if (boton == 3) {
            int x = evt.getX();
            int y = evt.getY();
            opciones.show(fondoArchivos, x, y);
        }
    }//GEN-LAST:event_fondoArchivosMouseClicked

    private void nombreArchivoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreArchivoMouseClicked
        nombreArchivo.setText(null);
        nombreArchivo.setForeground(Color.BLACK);
    }//GEN-LAST:event_nombreArchivoMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//        Principal framePrincipal = (Principal) getParent();
//
//        if (framePrincipal.txtGuardar == true) {
//            botonCrear.setVisible(false);
//            botonGuardar.setVisible(true);
//            nombreArchivo.setText("Ingrese nombre del documento.");
//        }

    }//GEN-LAST:event_formWindowOpened
    ArrayList<String> nombresRegistrados = new ArrayList<>();
    private void botonGuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonGuardarMouseClicked

        Principal framePrincipal = (Principal) getParent();
        JTextArea temp = framePrincipal.editorTexto.retornarTexto();

        String nombre = nombreArchivo.getText();
        String contenido = temp.getText();
        String tipo = "";
        try {
            tipo = (String) tipoArchivo.getSelectedItem();

        } catch (Exception E) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar el tipo de archivo");
            return;

        }

        if (tipo != ".txt") {
            JOptionPane.showMessageDialog(this, "Este documento debe ser forzosamente de tipo .txt");
            return;
        }
        String fecha = LocalDate.now().toString();

        boolean verf = verificarNombre(nombre);

        if (verf == true) {
            JOptionPane.showMessageDialog(this, "Ya hay un archivo con ese nombre, cambielo.");
            return;
        }

        nombresRegistrados.add(nombre);
        if (nombre.isEmpty() || nombre.equals("Ingrese nombre de la carpeta")) {
            JOptionPane.showMessageDialog(this, "Debe darle un nombre al documento");
            return;
        }

        int tamaño = contenido.length();
        archivosTxt nuevoArchivoTxt = new archivosTxt(nombre, fecha, contenido, tipo, tamaño);
        File nuevoArchivo = new File(nombre + tipo);

        nuevoArchivoTxt.guardarArchivo(nuevoArchivo);
        try {

            int columna = tablaArchivos.getSelectedColumn();
            int fila = tablaArchivos.getSelectedRow();

            DefaultTableModel modeloTabla = (DefaultTableModel) tablaArchivos.getModel();

            String datoN = "";
            for (int i = 0; i < modeloTabla.getRowCount(); i++) {
                for (int j = 0; j < modeloTabla.getColumnCount(); j++) {
                    if (i == fila && j == 0) {
                        Object dato = modeloTabla.getValueAt(i, j);
                        datoN = (String) dato;

                    }
                }

            }
            for (int i = 0; i < carpetasCreadas.size(); i++) {
                if (carpetasCreadas.get(i).nombre.equals(datoN)) {
                    carpetasCreadas.get(i).añadirArchivo(nuevoArchivoTxt);
                    JOptionPane.showMessageDialog(this, "Documento exitosamente guardado.");
                }
            }

//            if (valor instanceof carpetasArchivos) {
//                carpetasArchivos archivoSeleccionado = (carpetasArchivos) valor;
//                archivoSeleccionado.añadirArchivo(nuevoArchivoTxt);
//            }
            framePrincipal.txtGuardar = false;
            panelArchivos.setVisible(false);

        } catch (Exception E) {
            JOptionPane.showMessageDialog(this, "Asegurese de seleccionar una carpeta");
        }


    }//GEN-LAST:event_botonGuardarMouseClicked
    public boolean verificarNombre(String nombre) {
        boolean verf = false;
        for (int i = 0; i < nombresRegistrados.size(); i++) {
            if (nombresRegistrados.get(i).equals(nombre)) {
                verf = true;
            }
        }
        return verf;
    }
    private void tablaArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaArchivosMouseClicked

        if (evt.getButton() == java.awt.event.MouseEvent.BUTTON1 && evt.getClickCount() == 2) {
            int fila = tablaArchivos.getSelectedRow();

            if (fila != -1) {
                DefaultTableModel modeloTabla = (DefaultTableModel) tablaArchivos.getModel();
                Object dato = modeloTabla.getValueAt(fila, 0);

                if (dato != null) {
                    // .trim() elimina espacios transparentes al inicio o al final
                    String datoN = dato.toString().trim();
                    int ubicacion = -1;

                    // Comparación flexible
                    for (int i = 0; i < carpetasCreadas.size(); i++) {
                        if (carpetasCreadas.get(i).nombre.trim().equalsIgnoreCase(datoN)) {
                            ubicacion = i;
                            break;
                        }
                    }

                    if (ubicacion != -1) {
                        carpetasArchivos temp = carpetasCreadas.get(ubicacion);
                        ArrayList<archivosTxt> archivos = temp.archivosCarpeta;

                        DefaultTableModel modeloTablaArchivos = (DefaultTableModel) tablaContenidoArchivos.getModel();
                        modeloTablaArchivos.setRowCount(0);

                        for (archivosTxt arc : archivos) {
                            String[] datos = {arc.nombre, arc.fechaCreado, arc.tipo, arc.tamaño + ""};
                            modeloTablaArchivos.addRow(datos);
                        }

                        // Opcional: mostrar la ruta actual en el JTextField de arriba
                        ruta.setText(temp.nombre);

                        tablaArchivos.setVisible(false);
                        tablaContenidoArchivos.setVisible(true);
                    } else {
                        System.out.println("No se encontró la carpeta con el nombre: '" + datoN + "'");
                    }
                }
            }
        }

    }//GEN-LAST:event_tablaArchivosMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Principal framePrincipal = (Principal) getParent();

        if (framePrincipal.txtGuardar == true) {
            panelArchivos.setVisible(true);
            botonCrear.setVisible(false);
            botonGuardar.setVisible(true);
            nombreArchivo.setText("Ingrese nombre del documento.");
        }
    }//GEN-LAST:event_formWindowActivated

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void rutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rutaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rutaActionPerformed

    private void tablaContenidoArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaContenidoArchivosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaContenidoArchivosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ExploradorDeArchivos dialog = new ExploradorDeArchivos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCrear;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JTextField buscarArchivo;
    private javax.swing.JPanel carpetas;
    private javax.swing.JMenuItem crearCarpeta;
    private javax.swing.JPanel fondoArchivos;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombreArchivo;
    private javax.swing.JMenu nuevo;
    private javax.swing.JPopupMenu opciones;
    private javax.swing.JPanel panelArchivo;
    private javax.swing.JPanel panelArchivos;
    private javax.swing.JTextField ruta;
    private javax.swing.JTable tablaArchivos;
    private javax.swing.JScrollPane tablaContenido;
    private javax.swing.JTable tablaContenidoArchivos;
    private javax.swing.JComboBox<String> tipoArchivo;
    // End of variables declaration//GEN-END:variables
}
