/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectofinal_p2_jorgerush;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.GraphicsEnvironment;
import javax.swing.SpinnerListModel;

/**
 *
 * @author Jorge Rush
 */
public class modificarPantalla extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modificarPantalla.class.getName());

    /**
     * Creates new form modificarColoresPantalla
     */
    public modificarPantalla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        panelPantalla.setVisible(false);
        panelFuentes.setVisible(false);
        eleccionPantalla.setVisible(false);
        eleccionExternos.setVisible(false);
        Imagen.setVisible(false);
        ColorSolido.setVisible(false);

        DefaultComboBoxModel model = new DefaultComboBoxModel();
        colores.setModel(model);
        colores2.setModel(model);
        coloresFuente.setModel(model);
        coloresAñadir(model);

        String[] nombresFuentes = GraphicsEnvironment
                .getLocalGraphicsEnvironment()
                .getAvailableFontFamilyNames();

        SpinnerListModel modeloFuentes = new SpinnerListModel(nombresFuentes);
        spinnerFuente.setModel(modeloFuentes);

    }

    public void coloresAñadir(DefaultComboBoxModel model) {

        Colores negro = new Colores("Negro", Color.BLACK);
        Colores azul = new Colores("Azul", Color.BLUE);
        Colores rojo = new Colores("Rojo", Color.RED);
        Colores cyan = new Colores("Cyan", Color.CYAN);
        Colores grisOscuro = new Colores("Gris Oscuro", Color.DARK_GRAY);
        Colores verde = new Colores("Verde", Color.GREEN);
        Colores naranja = new Colores("Naranja", Color.ORANGE);
        Colores rosado = new Colores("Rosado", Color.PINK);
        Colores blanco = new Colores("Blanco", Color.WHITE);
        Colores amarillo = new Colores("Amarillo", Color.YELLOW);
        Colores gris = new Colores("Gris", Color.GRAY);
        Colores grisSuave = new Colores("Gris Suave", Color.LIGHT_GRAY);
        Colores magenta = new Colores("Magenta", Color.MAGENTA);
        Colores[] colores = {
            negro, azul, rojo, verde, amarillo, naranja, rosado, magenta, blanco, gris, grisSuave, grisOscuro, cyan};
        for (int i = 0; i < colores.length; i++) {
            model.addElement(colores[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarColoresPantalla = new javax.swing.JPanel();
        Fuentes = new javax.swing.JButton();
        panelFuentes = new javax.swing.JPanel();
        tituloConfiguracion = new javax.swing.JLabel();
        tituloConfiguracion2 = new javax.swing.JLabel();
        estiloFuente = new javax.swing.JLabel();
        tituloConfiguracion4 = new javax.swing.JLabel();
        coloresFuente = new javax.swing.JComboBox<>();
        spinnerFuente = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        ejemploFuente = new javax.swing.JTextArea();
        tamañoFuente = new javax.swing.JSpinner();
        Plain = new javax.swing.JButton();
        Bold = new javax.swing.JButton();
        BoldItalic = new javax.swing.JButton();
        Italic = new javax.swing.JButton();
        tituloConfiguracion3 = new javax.swing.JLabel();
        confirmarFuente = new javax.swing.JButton();
        panelPantalla = new javax.swing.JPanel();
        aspectosExternos = new javax.swing.JButton();
        fondoPm = new javax.swing.JButton();
        eleccionExternos = new javax.swing.JPanel();
        ColorSolido2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        colores2 = new javax.swing.JComboBox<>();
        seleccionColor3 = new javax.swing.JButton();
        barraN1 = new javax.swing.JRadioButton();
        barraT1 = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        R1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        G1 = new javax.swing.JTextField();
        B1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        seleccionColor4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        barraT = new javax.swing.JRadioButton();
        barraN = new javax.swing.JRadioButton();
        eleccionPantalla = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        seleccionFondo = new javax.swing.JComboBox<>();
        ColorSolido = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        colores = new javax.swing.JComboBox<>();
        seleccionColor1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        R = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        G = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        seleccionColor2 = new javax.swing.JButton();
        Imagen = new javax.swing.JPanel();
        ColorSolido1 = new javax.swing.JPanel();
        lago = new javax.swing.JButton();
        nevada = new javax.swing.JButton();
        tarde = new javax.swing.JButton();
        rancho = new javax.swing.JButton();
        elegirFondom = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        Pantalla = new javax.swing.JButton();
        fondo = new javax.swing.JPanel();
        tituloConfiguracion1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editarColoresPantalla.setBackground(new java.awt.Color(255, 255, 255));
        editarColoresPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Fuentes.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Fuentes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/PF1.png"))); // NOI18N
        Fuentes.setText("Fuentes");
        Fuentes.setBorder(null);
        Fuentes.setFocusPainted(false);
        Fuentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FuentesMouseClicked(evt);
            }
        });
        Fuentes.addActionListener(this::FuentesActionPerformed);
        editarColoresPantalla.add(Fuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 100, 30));

        panelFuentes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tituloConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tituloConfiguracion.setText("Color:");
        panelFuentes.add(tituloConfiguracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, -1, 20));

        tituloConfiguracion2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tituloConfiguracion2.setText("Ejemplar:");
        panelFuentes.add(tituloConfiguracion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        estiloFuente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estiloFuente.setText("Estilo de Fuente:");
        panelFuentes.add(estiloFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        tituloConfiguracion4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tituloConfiguracion4.setText("Tamaño:");
        panelFuentes.add(tituloConfiguracion4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, 40));

        coloresFuente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        coloresFuente.addActionListener(this::coloresFuenteActionPerformed);
        panelFuentes.add(coloresFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, 90, -1));

        spinnerFuente.addChangeListener(this::spinnerFuenteStateChanged);
        panelFuentes.add(spinnerFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 130, -1));

        ejemploFuente.setColumns(20);
        ejemploFuente.setRows(5);
        ejemploFuente.setText("¿Sabias que \"WitZig\" arcaicamente significa \"Ingenioso\" en Aleman?");
        jScrollPane1.setViewportView(ejemploFuente);

        panelFuentes.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 480, 110));

        tamañoFuente.setModel(new javax.swing.SpinnerNumberModel(10, null, null, 1));
        tamañoFuente.addChangeListener(this::tamañoFuenteStateChanged);
        panelFuentes.add(tamañoFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 20, 50, -1));

        Plain.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Plain.setText("T");
        Plain.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PlainMouseClicked(evt);
            }
        });
        panelFuentes.add(Plain, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, 20));

        Bold.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Bold.setText("N");
        Bold.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoldMouseClicked(evt);
            }
        });
        panelFuentes.add(Bold, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, 20));

        BoldItalic.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        BoldItalic.setText("M");
        BoldItalic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BoldItalicMouseClicked(evt);
            }
        });
        panelFuentes.add(BoldItalic, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, -1, 20));

        Italic.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        Italic.setText("K");
        Italic.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ItalicMouseClicked(evt);
            }
        });
        panelFuentes.add(Italic, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, -1, 20));

        tituloConfiguracion3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tituloConfiguracion3.setText("Tipo de Fuente:");
        panelFuentes.add(tituloConfiguracion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        confirmarFuente.setText("Seleccionar Como Fuente Predeterminada");
        confirmarFuente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                confirmarFuenteMouseClicked(evt);
            }
        });
        panelFuentes.add(confirmarFuente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        editarColoresPantalla.add(panelFuentes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 530, 290));

        panelPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aspectosExternos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        aspectosExternos.setText("Aspectos Externos");
        aspectosExternos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aspectosExternosMouseClicked(evt);
            }
        });
        aspectosExternos.addActionListener(this::aspectosExternosActionPerformed);
        panelPantalla.add(aspectosExternos, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, 30));

        fondoPm.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        fondoPm.setText("Fondo de Pantalla");
        fondoPm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fondoPmMouseClicked(evt);
            }
        });
        fondoPm.addActionListener(this::fondoPmActionPerformed);
        panelPantalla.add(fondoPm, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 140, 30));

        eleccionExternos.setBackground(new java.awt.Color(204, 255, 153));

        ColorSolido2.setBackground(new java.awt.Color(255, 255, 255));
        ColorSolido2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Seleccionar Color:");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        colores2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(colores2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 92, -1));

        seleccionColor3.setText("Elegir");
        seleccionColor3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionColor3MouseClicked(evt);
            }
        });
        jPanel4.add(seleccionColor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        barraN1.setText("Barra de Navegacion");
        barraN1.setFocusPainted(false);
        jPanel4.add(barraN1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        barraT1.setText("Barra de Tareas");
        barraT1.setFocusPainted(false);
        jPanel4.add(barraT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Seleccione Elemento/s:");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jTabbedPane2.addTab("Seleccionar Color", jPanel4);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("Color Personalizado:");

        jLabel14.setText("R");

        jLabel15.setText("G");

        jLabel16.setText("B");

        seleccionColor4.setText("Elegir");
        seleccionColor4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionColor4MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Seleccione Elemento/s:");

        barraT.setText("Barra de Tareas");
        barraT.setFocusPainted(false);

        barraN.setText("Barra de Navegacion");
        barraN.setFocusPainted(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(26, 26, 26)
                                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(32, 32, 32)))
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel15)
                                .addGap(54, 54, 54)
                                .addComponent(jLabel16)))
                        .addGap(18, 18, 18)
                        .addComponent(seleccionColor4))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(barraT)
                            .addComponent(barraN)
                            .addComponent(jLabel3))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(barraN)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seleccionColor4)))
                .addGap(14, 14, 14))
        );

        jTabbedPane2.addTab("Color Personalizado", jPanel5);

        ColorSolido2.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 530, 190));

        javax.swing.GroupLayout eleccionExternosLayout = new javax.swing.GroupLayout(eleccionExternos);
        eleccionExternos.setLayout(eleccionExternosLayout);
        eleccionExternosLayout.setHorizontalGroup(
            eleccionExternosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorSolido2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        eleccionExternosLayout.setVerticalGroup(
            eleccionExternosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ColorSolido2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
        );

        panelPantalla.add(eleccionExternos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 530, 240));

        eleccionPantalla.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Personalizar el Fondo de Pantalla:");

        seleccionFondo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imagen", "Color Solido" }));
        seleccionFondo.addActionListener(this::seleccionFondoActionPerformed);

        ColorSolido.setBackground(new java.awt.Color(255, 255, 255));
        ColorSolido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Seleccionar Color:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        colores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(colores, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 92, -1));

        seleccionColor1.setText("Elegir");
        seleccionColor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionColor1MouseClicked(evt);
            }
        });
        jPanel2.add(seleccionColor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        jTabbedPane1.addTab("Seleccionar Color", jPanel2);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Color Personalizado:");

        jLabel7.setText("R");

        jLabel8.setText("G");

        jLabel9.setText("B");

        seleccionColor2.setText("Elegir");
        seleccionColor2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionColor2MouseClicked(evt);
            }
        });
        seleccionColor2.addActionListener(this::seleccionColor2ActionPerformed);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel6)
                        .addGap(26, 26, 26)
                        .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addGap(32, 32, 32)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(seleccionColor2))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel8)
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(G, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(B, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(seleccionColor2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Color Personalizado", jPanel3);

        ColorSolido.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 150));

        Imagen.setBackground(new java.awt.Color(255, 255, 255));
        Imagen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ColorSolido1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lago.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondosPantalla/FT4.png"))); // NOI18N
        lago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lagoMouseClicked(evt);
            }
        });
        ColorSolido1.add(lago, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, 87, 83));

        nevada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondosPantalla/FT1.png"))); // NOI18N
        nevada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nevadaMouseClicked(evt);
            }
        });
        ColorSolido1.add(nevada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 87, 83));

        tarde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondosPantalla/F2.jpg"))); // NOI18N
        tarde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tardeMouseClicked(evt);
            }
        });
        ColorSolido1.add(tarde, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 87, 83));

        rancho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondosPantalla/FT3.png"))); // NOI18N
        rancho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ranchoMouseClicked(evt);
            }
        });
        ColorSolido1.add(rancho, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 87, 83));

        elegirFondom.setText("Confirmar");
        elegirFondom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                elegirFondomMouseClicked(evt);
            }
        });
        ColorSolido1.add(elegirFondom, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, -1, -1));

        jLabel10.setText("Seleccione un Fondo de Pantalla Predeterminado:");
        ColorSolido1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, -1, -1));

        Imagen.add(ColorSolido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 520, 150));

        javax.swing.GroupLayout eleccionPantallaLayout = new javax.swing.GroupLayout(eleccionPantalla);
        eleccionPantalla.setLayout(eleccionPantallaLayout);
        eleccionPantallaLayout.setHorizontalGroup(
            eleccionPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eleccionPantallaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4)
                .addGap(16, 16, 16)
                .addComponent(seleccionFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(eleccionPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ColorSolido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(eleccionPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(eleccionPantallaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Imagen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        eleccionPantallaLayout.setVerticalGroup(
            eleccionPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(eleccionPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(eleccionPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(seleccionFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ColorSolido, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(eleccionPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, eleccionPantallaLayout.createSequentialGroup()
                    .addContainerGap(36, Short.MAX_VALUE)
                    .addComponent(Imagen, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(28, Short.MAX_VALUE)))
        );

        panelPantalla.add(eleccionPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 530, 240));

        editarColoresPantalla.add(panelPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 530, 290));

        Pantalla.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Pantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/PM1.png"))); // NOI18N
        Pantalla.setText("Pantalla");
        Pantalla.setBorder(null);
        Pantalla.setFocusPainted(false);
        Pantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PantallaMouseClicked(evt);
            }
        });
        Pantalla.addActionListener(this::PantallaActionPerformed);
        editarColoresPantalla.add(Pantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 30));

        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        editarColoresPantalla.add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 530, 290));

        tituloConfiguracion1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        tituloConfiguracion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/P2.png"))); // NOI18N
        tituloConfiguracion1.setText("Personalización de Pantalla");
        tituloConfiguracion1.setOpaque(true);
        editarColoresPantalla.add(tituloConfiguracion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        getContentPane().add(editarColoresPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FuentesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FuentesActionPerformed

    private void aspectosExternosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aspectosExternosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aspectosExternosActionPerformed

    private void seleccionColor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionColor1MouseClicked
        Object eleccion = colores.getSelectedItem();

        if (eleccion instanceof Colores) {

            Colores colorElegido = (Colores) eleccion;
            Principal framePrincipal = (Principal) getParent();
            framePrincipal.ocultarFondo(false);
            framePrincipal.colorFondoP(colorElegido.color);

        }
    }//GEN-LAST:event_seleccionColor1MouseClicked

    private void PantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PantallaActionPerformed

    private void fondoPmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fondoPmActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fondoPmActionPerformed

    private void seleccionColor2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionColor2MouseClicked
        try {
            String Rn = R.getText();
            String Gn = G.getText();
            String Bn = B.getText();

            int R1 = Integer.parseInt(Rn);
            int G1 = Integer.parseInt(Gn);
            int B1 = Integer.parseInt(Bn);

            Color colorElegido = new Color(R1, G1, B1);
            Principal framePrincipal = (Principal) getParent();
            framePrincipal.ocultarFondo(false);
            framePrincipal.colorFondoP(colorElegido);

        } catch (Exception E) {
            JOptionPane.showMessageDialog(this, "Debe introducir un numero valido donde se le indica.");
            return;
        }

    }//GEN-LAST:event_seleccionColor2MouseClicked
    public void ocultarVentanas(boolean mostrar) {
        eleccionPantalla.setVisible(mostrar);
        Imagen.setVisible(mostrar);
        ColorSolido.setVisible(mostrar);
    }
    private void seleccionFondoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionFondoActionPerformed
        Object elegido = seleccionFondo.getSelectedItem();

        String eleccion = (String) elegido;
        System.out.println(eleccion);
        if (eleccion.equals("Color Solido")) {
            Imagen.setVisible(false);
            ColorSolido.setVisible(true);

        } else if (eleccion.equals("Imagen")) {
            ColorSolido.setVisible(false);
            Imagen.setVisible(true);
        }

    }//GEN-LAST:event_seleccionFondoActionPerformed
    int nevadaElegido = 0;
    int tardeElegido = 0;
    int rachoElegido = 0;
    int lagoElegido = 0;

    private void nevadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nevadaMouseClicked
        nevadaElegido = 1;
        tardeElegido = 0;
        rachoElegido = 0;
        lagoElegido = 0;
    }//GEN-LAST:event_nevadaMouseClicked

    private void tardeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tardeMouseClicked
        nevadaElegido = 0;
        tardeElegido = 2;
        rachoElegido = 0;
        lagoElegido = 0;
    }//GEN-LAST:event_tardeMouseClicked

    private void ranchoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ranchoMouseClicked
        nevadaElegido = 0;
        tardeElegido = 0;
        rachoElegido = 3;
        lagoElegido = 0;
    }//GEN-LAST:event_ranchoMouseClicked

    private void lagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lagoMouseClicked
        nevadaElegido = 0;
        tardeElegido = 0;
        rachoElegido = 0;
        lagoElegido = 4;
    }//GEN-LAST:event_lagoMouseClicked

    private void elegirFondomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elegirFondomMouseClicked
        Principal framePrincipal = (Principal) getParent();
        framePrincipal.ocultarFondo(true);
        if (nevadaElegido != 0) {

            framePrincipal.cambiarFondo(1);
        } else if (tardeElegido != 0) {

            framePrincipal.cambiarFondo(2);
        } else if (rachoElegido != 0) {

            framePrincipal.cambiarFondo(3);
        } else if (lagoElegido != 0) {

            framePrincipal.cambiarFondo(4);
        } else {
            JOptionPane.showMessageDialog(this, "Debe darle click a un fondo, posterior a eso confirmar su seleccion.");

        }
    }//GEN-LAST:event_elegirFondomMouseClicked

    private void fondoPmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fondoPmMouseClicked
        eleccionExternos.setVisible(false);
        eleccionPantalla.setVisible(true);
    }//GEN-LAST:event_fondoPmMouseClicked

    private void seleccionColor4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionColor4MouseClicked
        try {
            String Rn = R1.getText();
            String Gn = G1.getText();
            String Bn = B1.getText();

            int R1 = Integer.parseInt(Rn);
            int G1 = Integer.parseInt(Gn);
            int B1 = Integer.parseInt(Bn);

            Color colorElegido = new Color(R1, G1, B1);
            Principal framePrincipal = (Principal) getParent();
            if (barraT.isSelected()) {
                framePrincipal.colorBarraT(colorElegido);
            }

            if (barraN.isSelected()) {
                framePrincipal.colorBarraN(colorElegido);
            }

        } catch (Exception E) {
            JOptionPane.showMessageDialog(this, "Debe introducir un numero valido donde se le indica.");
            return;
        }
    }//GEN-LAST:event_seleccionColor4MouseClicked

    private void seleccionColor3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionColor3MouseClicked
        Object eleccion = colores.getSelectedItem();
        if (eleccion instanceof Colores) {
            Colores colorElegido = (Colores) eleccion;
            Principal framePrincipal = (Principal) getParent();
            boolean verf = false;
            if (barraT1.isSelected()) {
                framePrincipal.colorBarraT(colorElegido.color);
                verf = true;
            }

            if (barraN1.isSelected()) {
                framePrincipal.colorBarraN(colorElegido.color);
                verf = true;
            }
            if (verf == false) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la pantalla.");
            }
        }
    }//GEN-LAST:event_seleccionColor3MouseClicked

    private void aspectosExternosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aspectosExternosMouseClicked
        eleccionPantalla.setVisible(false);
        eleccionExternos.setVisible(true);
    }//GEN-LAST:event_aspectosExternosMouseClicked

    private void PantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PantallaMouseClicked
        panelPantalla.setVisible(true);
        panelFuentes.setVisible(false);
    }//GEN-LAST:event_PantallaMouseClicked

    private void FuentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FuentesMouseClicked
        panelPantalla.setVisible(false);
        panelFuentes.setVisible(true);
    }//GEN-LAST:event_FuentesMouseClicked


    private void spinnerFuenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinnerFuenteStateChanged

        String fuente = (String) spinnerFuente.getValue();
        Font fuenteActual = ejemploFuente.getFont();
        int estilo = fuenteActual.getStyle();
        int tamaño = fuenteActual.getSize();
        Font fuenteEjemplo = new Font(fuente, estilo, tamaño);
        ejemploFuente.setFont(fuenteEjemplo);
        Color colorEleccion = ejemploFuente.getForeground();
        ejemploFuente.setForeground(colorEleccion);
    }//GEN-LAST:event_spinnerFuenteStateChanged

    int estiloFuenteN = 0;

    private void PlainMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PlainMouseClicked
        estiloFuenteN = 0;
        Font fuenteActual = ejemploFuente.getFont();
        String nombreActual = fuenteActual.getName();
        int tamaño = fuenteActual.getSize();
        Font fuenteEjemplo = new Font(nombreActual, estiloFuenteN, tamaño);
        Color colorEleccion = ejemploFuente.getForeground();
        ejemploFuente.setFont(fuenteEjemplo);
        ejemploFuente.setForeground(colorEleccion);
    }//GEN-LAST:event_PlainMouseClicked

    private void BoldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoldMouseClicked
        estiloFuenteN = 1;
        Font fuenteActual = ejemploFuente.getFont();
        String nombreActual = fuenteActual.getName();
        int tamaño = fuenteActual.getSize();
        Font fuenteEjemplo = new Font(nombreActual, estiloFuenteN, tamaño);
        ejemploFuente.setFont(fuenteEjemplo);
        Color colorEleccion = ejemploFuente.getForeground();
        ejemploFuente.setForeground(colorEleccion);
    }//GEN-LAST:event_BoldMouseClicked

    private void ItalicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ItalicMouseClicked
        estiloFuenteN = 2;
        Font fuenteActual = ejemploFuente.getFont();
        String nombreActual = fuenteActual.getName();
        int tamaño = fuenteActual.getSize();
        Font fuenteEjemplo = new Font(nombreActual, estiloFuenteN, tamaño);
        Color colorEleccion = ejemploFuente.getForeground();
        ejemploFuente.setFont(fuenteEjemplo);
        ejemploFuente.setForeground(colorEleccion);
    }//GEN-LAST:event_ItalicMouseClicked

    private void BoldItalicMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BoldItalicMouseClicked
        estiloFuenteN = 3;
        Font fuenteActual = ejemploFuente.getFont();
        String nombreActual = fuenteActual.getName();
        int tamaño = fuenteActual.getSize();
        Font fuenteEjemplo = new Font(nombreActual, estiloFuenteN, tamaño);
        Color colorEleccion = ejemploFuente.getForeground();
        ejemploFuente.setFont(fuenteEjemplo);
        ejemploFuente.setForeground(colorEleccion);
    }//GEN-LAST:event_BoldItalicMouseClicked

    private void tamañoFuenteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tamañoFuenteStateChanged
        Font fuenteActual = ejemploFuente.getFont();
        String nombreActual = fuenteActual.getName();
        int estilo = fuenteActual.getStyle();
        int tamaño = (int) tamañoFuente.getValue();
        Font fuenteEjemplo = new Font(nombreActual, estilo, tamaño);
        ejemploFuente.setFont(fuenteEjemplo);
        Color colorEleccion = ejemploFuente.getForeground();
        ejemploFuente.setForeground(colorEleccion);
    }//GEN-LAST:event_tamañoFuenteStateChanged

    private void coloresFuenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coloresFuenteActionPerformed
        Object colorElegido = coloresFuente.getSelectedItem();
        if (colorElegido instanceof Colores) {
            Colores temp = (Colores) colorElegido;
            Color colorEleccion = temp.color;
            ejemploFuente.setForeground(colorEleccion);
        }
    }//GEN-LAST:event_coloresFuenteActionPerformed

    private void confirmarFuenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_confirmarFuenteMouseClicked
        try {
            String fuente = (String) spinnerFuente.getValue();

            int estilo = estiloFuenteN;
            int tamaño = (int) tamañoFuente.getValue();
            Font fuenteConf = new Font(fuente, estilo, tamaño);
            Principal framePrincipal = (Principal) getParent();
            framePrincipal.cambiarFontPantallaInicio(fuenteConf);

            Colores colorEleccion = (Colores) coloresFuente.getSelectedItem();
            Color colorElegido = colorEleccion.color;
            framePrincipal.cambiarColorFontPI(colorElegido);
        } catch (Exception E) {
            Font fuenteActual = ejemploFuente.getFont();
            
            Principal framePrincipal = (Principal) getParent();
            framePrincipal.cambiarFontPantallaInicio(fuenteActual);
            Color colorDef=ejemploFuente.getForeground();
            framePrincipal.cambiarColorFontPI(colorDef);

        }


    }//GEN-LAST:event_confirmarFuenteMouseClicked

    private void seleccionColor2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionColor2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seleccionColor2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                modificarPantalla dialog = new modificarPantalla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B;
    private javax.swing.JTextField B1;
    private javax.swing.JButton Bold;
    private javax.swing.JButton BoldItalic;
    private javax.swing.JPanel ColorSolido;
    private javax.swing.JPanel ColorSolido1;
    private javax.swing.JPanel ColorSolido2;
    private javax.swing.JButton Fuentes;
    private javax.swing.JTextField G;
    private javax.swing.JTextField G1;
    private javax.swing.JPanel Imagen;
    private javax.swing.JButton Italic;
    private javax.swing.JButton Pantalla;
    private javax.swing.JButton Plain;
    private javax.swing.JTextField R;
    private javax.swing.JTextField R1;
    private javax.swing.JButton aspectosExternos;
    private javax.swing.JRadioButton barraN;
    private javax.swing.JRadioButton barraN1;
    private javax.swing.JRadioButton barraT;
    private javax.swing.JRadioButton barraT1;
    private javax.swing.JComboBox<String> colores;
    private javax.swing.JComboBox<String> colores2;
    private javax.swing.JComboBox<String> coloresFuente;
    private javax.swing.JButton confirmarFuente;
    private javax.swing.JPanel editarColoresPantalla;
    private javax.swing.JTextArea ejemploFuente;
    private javax.swing.JPanel eleccionExternos;
    private javax.swing.JPanel eleccionPantalla;
    private javax.swing.JButton elegirFondom;
    private javax.swing.JLabel estiloFuente;
    private javax.swing.JPanel fondo;
    private javax.swing.JButton fondoPm;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JButton lago;
    private javax.swing.JButton nevada;
    private javax.swing.JPanel panelFuentes;
    private javax.swing.JPanel panelPantalla;
    private javax.swing.JButton rancho;
    private javax.swing.JButton seleccionColor1;
    private javax.swing.JButton seleccionColor2;
    private javax.swing.JButton seleccionColor3;
    private javax.swing.JButton seleccionColor4;
    private javax.swing.JComboBox<String> seleccionFondo;
    private javax.swing.JSpinner spinnerFuente;
    private javax.swing.JSpinner tamañoFuente;
    private javax.swing.JButton tarde;
    private javax.swing.JLabel tituloConfiguracion;
    private javax.swing.JLabel tituloConfiguracion1;
    private javax.swing.JLabel tituloConfiguracion2;
    private javax.swing.JLabel tituloConfiguracion3;
    private javax.swing.JLabel tituloConfiguracion4;
    // End of variables declaration//GEN-END:variables
}
