/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyectofinal_p2_jorgerush;

import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jorge Rush
 */
public class modificarColoresPantalla extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(modificarColoresPantalla.class.getName());

    /**
     * Creates new form modificarColoresPantalla
     */
    public modificarColoresPantalla(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        colores.setModel(model);
        coloresAñadir(model);
    }

    public void coloresAñadir(DefaultComboBoxModel model) {

        Colores negro = new Colores("Negro", Color.BLACK);
        Colores azul = new Colores("Azul", Color.BLUE);
        Colores rojo = new Colores("Rojo", Color.RED);
        Colores cyan = new Colores("Cyan", Color.CYAN);
        Colores grisOscuro = new Colores("Gris Oscuro", Color.DARK_GRAY);
        Colores verde = new Colores("Verde", Color.GREEN);
        Colores naranja = new Colores("Naranja", Color.ORANGE);
        Colores rosado = new Colores("Rosado", Color.PINK);
        Colores blanco = new Colores("Blanco", Color.WHITE);
        Colores amarillo = new Colores("Amarillo", Color.YELLOW);
        Colores gris = new Colores("Gris", Color.GRAY);
        Colores grisSuave = new Colores("Gris Suave", Color.LIGHT_GRAY);
        Colores magenta = new Colores("Magenta", Color.MAGENTA);
        Colores[] colores = {
            negro, azul, rojo, verde, amarillo, naranja, rosado, magenta, blanco, gris, grisSuave, grisOscuro, cyan};
        for (int i = 0; i < colores.length; i++) {
            model.addElement(colores[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editarColoresPantalla = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        colores = new javax.swing.JComboBox<>();
        seleccionColor = new javax.swing.JButton();
        fondoP = new javax.swing.JRadioButton();
        barraN = new javax.swing.JRadioButton();
        barraT = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        editarColoresPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione Elemento:");
        editarColoresPantalla.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        colores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        editarColoresPantalla.add(colores, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 92, -1));

        seleccionColor.setText("Elegir");
        seleccionColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seleccionColorMouseClicked(evt);
            }
        });
        editarColoresPantalla.add(seleccionColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, -1, -1));

        fondoP.setText("Fondo de Pantalla");
        fondoP.setFocusPainted(false);
        editarColoresPantalla.add(fondoP, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        barraN.setText("Barra de Navegacion");
        barraN.setFocusPainted(false);
        editarColoresPantalla.add(barraN, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        barraT.setText("Barra de Tareas");
        barraT.setFocusPainted(false);
        editarColoresPantalla.add(barraT, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Seleccionar Color:");
        editarColoresPantalla.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(editarColoresPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editarColoresPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionColorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seleccionColorMouseClicked
        Object eleccion = colores.getSelectedItem();
        if (eleccion instanceof Colores) {
            Colores colorElegido = (Colores) eleccion;
            Principal framePrincipal = (Principal) getParent();
            if (barraT.isSelected()) {
                framePrincipal.colorBarraT(colorElegido.color);
            } else if (fondoP.isSelected()) {
                framePrincipal.colorFondoP(colorElegido.color);
            } else if (barraN.isSelected()) {
                framePrincipal.colorBarraN(colorElegido.color);
            } else {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un elemento de la pantalla.");
            }

        }
    }//GEN-LAST:event_seleccionColorMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                modificarColoresPantalla dialog = new modificarColoresPantalla(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton barraN;
    private javax.swing.JRadioButton barraT;
    private javax.swing.JComboBox<String> colores;
    private javax.swing.JPanel editarColoresPantalla;
    private javax.swing.JRadioButton fondoP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton seleccionColor;
    // End of variables declaration//GEN-END:variables
}
