/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal_p2_jorgerush;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import javax.swing.UIManager;
import java.awt.Font;

/**
 *
 * @author Jorge Rush
 */
public class Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
   modificarPantalla modColor ;
   EditorTexto editorTexto;
    /**
     * Creates new form Principal
     */
    public Principal() {

        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }
        modColor = new modificarPantalla(this, false);
        editorTexto= new EditorTexto(this,false);
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);
        
        this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
//        this.setVisible(true);
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        SpinnerListModel modelLista = new SpinnerListModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void cambiarColorFontPI(Color color){
        BarraNavegacion.setForeground(color);
        
    }
    public void cambiarFontPantallaInicio(Font fuente){
        ModificarPantalla.setFont(fuente);
    }
    public void cambiarFondo(int i){
        
        if (i==1){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F1.png"));
            fondoImagen.setIcon(icono);
            FondoPantallaOg.setComponentZOrder(BarraTareas, 0);
            FondoPantallaOg.repaint();
        }else if (i==2){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F2.png"));
            fondoImagen.setIcon(icono);
            FondoPantallaOg.setComponentZOrder(BarraTareas, 0);
            FondoPantallaOg.repaint();
        }else if (i==3){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F3.png"));
            fondoImagen.setIcon(icono);
            FondoPantallaOg.setComponentZOrder(BarraTareas, 0);
            FondoPantallaOg.repaint();
        }else if (i==4){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F4.png"));
            fondoImagen.setIcon(icono);
            FondoPantallaOg.setComponentZOrder(BarraTareas, 0);
            FondoPantallaOg.repaint();
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        PopUpMenu = new javax.swing.JPopupMenu();
        Personalizar = new javax.swing.JMenuItem();
        FondoPantallaOg = new javax.swing.JPanel();
        BarraTareas = new javax.swing.JPanel();
        contenedor = new javax.swing.JPanel();
        explorarArchivos = new javax.swing.JButton();
        WitZig = new javax.swing.JButton();
        editorTexto1 = new javax.swing.JButton();
        FondoPantalla = new javax.swing.JPanel();
        fondoImagen = new javax.swing.JLabel();
        BarraNavegacion = new javax.swing.JMenuBar();
        LogoWitZig = new javax.swing.JMenu();
        ModificarPantalla = new javax.swing.JMenu();

        Personalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/P1.png"))); // NOI18N
        Personalizar.setText("Personalizar");
        Personalizar.addActionListener(this::PersonalizarActionPerformed);
        PopUpMenu.add(Personalizar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        FondoPantallaOg.setBackground(new java.awt.Color(255, 255, 255));
        FondoPantallaOg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FondoPantallaOgMouseClicked(evt);
            }
        });
        FondoPantallaOg.setLayout(new java.awt.GridBagLayout());

        BarraTareas.setPreferredSize(new java.awt.Dimension(445, 40));
        BarraTareas.setLayout(new java.awt.BorderLayout());

        contenedor.setOpaque(false);
        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 15, 2);
        flowLayout1.setAlignOnBaseline(true);
        contenedor.setLayout(flowLayout1);

        explorarArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/Ex1.png"))); // NOI18N
        explorarArchivos.setBorder(null);
        explorarArchivos.setContentAreaFilled(false);
        explorarArchivos.setFocusPainted(false);
        explorarArchivos.addActionListener(this::explorarArchivosActionPerformed);
        contenedor.add(explorarArchivos);

        WitZig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/W1.png"))); // NOI18N
        WitZig.setBorder(null);
        WitZig.setBorderPainted(false);
        WitZig.setContentAreaFilled(false);
        WitZig.setFocusPainted(false);
        contenedor.add(WitZig);

        editorTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/Ed1.png"))); // NOI18N
        editorTexto1.setBorder(null);
        editorTexto1.setContentAreaFilled(false);
        editorTexto1.setFocusPainted(false);
        editorTexto1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editorTexto1MouseClicked(evt);
            }
        });
        editorTexto1.addActionListener(this::editorTexto1ActionPerformed);
        contenedor.add(editorTexto1);

        BarraTareas.add(contenedor, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.PAGE_END;
        gridBagConstraints.weightx = 1.0;
        FondoPantallaOg.add(BarraTareas, gridBagConstraints);

        FondoPantalla.setBackground(new java.awt.Color(204, 204, 204));
        FondoPantalla.setLayout(new java.awt.GridBagLayout());

        fondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondosPantalla/F1.png"))); // NOI18N
        FondoPantalla.add(fondoImagen, new java.awt.GridBagConstraints());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 1);
        FondoPantallaOg.add(FondoPantalla, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(FondoPantallaOg, gridBagConstraints);

        BarraNavegacion.setBackground(new java.awt.Color(242, 242, 242));
        BarraNavegacion.setBorder(null);
        BarraNavegacion.setOpaque(true);

        LogoWitZig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/W2.png"))); // NOI18N
        BarraNavegacion.add(LogoWitZig);

        ModificarPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/P1.png"))); // NOI18N
        ModificarPantalla.setText("Personalizar");
        ModificarPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarPantallaMouseClicked(evt);
            }
        });
        ModificarPantalla.addActionListener(this::ModificarPantallaActionPerformed);
        BarraNavegacion.add(ModificarPantalla);

        setJMenuBar(BarraNavegacion);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ocultarFondo(boolean mostrar){
        fondoImagen.setVisible(mostrar);
    }
    private void explorarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorarArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_explorarArchivosActionPerformed
    public void aparecerElementos(boolean mostrar) {
        FondoPantalla.setVisible(mostrar);
    }
    private void ModificarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPantallaActionPerformed
        
        modColor.setLocationRelativeTo(this);
        modColor.setVisible(true);
    }//GEN-LAST:event_ModificarPantallaActionPerformed

    private void ModificarPantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarPantallaMouseClicked
       
        modColor.setLocationRelativeTo(this);
        modColor.setVisible(true);
    }//GEN-LAST:event_ModificarPantallaMouseClicked

    private void PersonalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonalizarActionPerformed
        modColor.setLocationRelativeTo(this);
        modColor.setVisible(true);
    }//GEN-LAST:event_PersonalizarActionPerformed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        
    }//GEN-LAST:event_formMouseClicked

    private void FondoPantallaOgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FondoPantallaOgMouseClicked
        int boton=evt.getButton();
        if (boton==1){
            //selecciona
        }else if (boton==3){
            int x=evt.getX();
            int y=evt.getY();
            PopUpMenu.show(FondoPantallaOg, x, y);
        }
    }//GEN-LAST:event_FondoPantallaOgMouseClicked

    private void editorTexto1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editorTexto1MouseClicked
        editorTexto.setLocationRelativeTo(this);
        editorTexto.setVisible(true);
    }//GEN-LAST:event_editorTexto1MouseClicked

    private void editorTexto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editorTexto1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editorTexto1ActionPerformed
    public void colorBarraN(Color color) {
        BarraNavegacion.setBackground(color);
    }

    public void colorBarraT(Color color) {
        BarraTareas.setBackground(color);
    }

    public void colorFondoP(Color color) {
        FondoPantalla.setBackground(color);
    }

    public void ocultarEdicionPantalla(boolean mostrar) {
//        editor.setVisible(mostrar);
//        editorElementos.setVisible(mostrar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraNavegacion;
    private javax.swing.JPanel BarraTareas;
    private javax.swing.JPanel FondoPantalla;
    private javax.swing.JPanel FondoPantallaOg;
    private javax.swing.JMenu LogoWitZig;
    private javax.swing.JMenu ModificarPantalla;
    private javax.swing.JMenuItem Personalizar;
    private javax.swing.JPopupMenu PopUpMenu;
    private javax.swing.JButton WitZig;
    private javax.swing.JPanel contenedor;
    private javax.swing.JButton editorTexto1;
    private javax.swing.JButton explorarArchivos;
    private javax.swing.JLabel fondoImagen;
    // End of variables declaration//GEN-END:variables
}
