/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyectofinal_p2_jorgerush;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SpinnerListModel;
import javax.swing.UIManager;
import java.awt.Font;

/**
 *
 * @author Jorge Rush
 */
public class Principal extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Principal.class.getName());
   modificarPantalla modColor ;
    /**
     * Creates new form Principal
     */
    public Principal() {

        try {
            com.formdev.flatlaf.FlatLightLaf.setup();
        } catch (Exception e) {
            e.printStackTrace();
        }
        modColor = new modificarPantalla(this, true);
        initComponents();
        
        DefaultComboBoxModel model = new DefaultComboBoxModel();

        SpinnerListModel modelLista = new SpinnerListModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    public void cambiarColorFontPI(Color color){
        ModificarPantalla.setForeground(color);
    }
    public void cambiarFontPantallaInicio(Font fuente){
        ModificarPantalla.setFont(fuente);
    }
    public void cambiarFondo(int i){
        
        if (i==1){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F1.png"));
            fondoImagen.setIcon(icono);
        }else if (i==2){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F2.jpg"));
            fondoImagen.setIcon(icono);
            
        }else if (i==3){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F3.png"));
            fondoImagen.setIcon(icono);
        }else if (i==4){
            Icon icono = new ImageIcon(getClass().getResource("/fondosPantalla/F4.png"));
            fondoImagen.setIcon(icono);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        FondoPantalla = new javax.swing.JPanel();
        BarraTareas = new javax.swing.JPanel();
        editorTexto1 = new javax.swing.JButton();
        explorarArchivos = new javax.swing.JButton();
        WitZig = new javax.swing.JButton();
        fondoImagen = new javax.swing.JLabel();
        BarraNavegacion = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        ModificarPantalla = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FondoPantalla.setBackground(new java.awt.Color(255, 255, 255));
        FondoPantalla.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraTareas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editorTexto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/Ed1.png"))); // NOI18N
        editorTexto1.setBorder(null);
        editorTexto1.setContentAreaFilled(false);
        editorTexto1.setFocusPainted(false);
        BarraTareas.add(editorTexto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 40, 40));

        explorarArchivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/Ex1.png"))); // NOI18N
        explorarArchivos.setBorder(null);
        explorarArchivos.setContentAreaFilled(false);
        explorarArchivos.setFocusPainted(false);
        explorarArchivos.addActionListener(this::explorarArchivosActionPerformed);
        BarraTareas.add(explorarArchivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, -1, 40));

        WitZig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/W1.png"))); // NOI18N
        WitZig.setBorder(null);
        WitZig.setBorderPainted(false);
        WitZig.setContentAreaFilled(false);
        WitZig.setFocusPainted(false);
        BarraTareas.add(WitZig, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 60, -1));

        FondoPantalla.add(BarraTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 420, 540, 40));

        fondoImagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/fondosPantalla/F1.png"))); // NOI18N
        FondoPantalla.add(fondoImagen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 460));

        jPanel1.add(FondoPantalla, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 460));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, 460));

        BarraNavegacion.setBackground(new java.awt.Color(242, 242, 242));
        BarraNavegacion.setBorder(null);
        BarraNavegacion.setOpaque(true);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/W2.png"))); // NOI18N
        BarraNavegacion.add(jMenu1);

        ModificarPantalla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/LogoTipos/P1.png"))); // NOI18N
        ModificarPantalla.setText("Personalizar");
        ModificarPantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarPantallaMouseClicked(evt);
            }
        });
        ModificarPantalla.addActionListener(this::ModificarPantallaActionPerformed);
        BarraNavegacion.add(ModificarPantalla);

        setJMenuBar(BarraNavegacion);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void ocultarFondo(boolean mostrar){
        fondoImagen.setVisible(mostrar);
    }
    private void explorarArchivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explorarArchivosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_explorarArchivosActionPerformed
    public void aparecerElementos(boolean mostrar) {
        FondoPantalla.setVisible(mostrar);
    }
    private void ModificarPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarPantallaActionPerformed
        
        modColor.setLocationRelativeTo(this);
        modColor.setVisible(true);
    }//GEN-LAST:event_ModificarPantallaActionPerformed

    private void ModificarPantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarPantallaMouseClicked
       
        modColor.setLocationRelativeTo(this);
        modColor.setVisible(true);
    }//GEN-LAST:event_ModificarPantallaMouseClicked
    public void colorBarraN(Color color) {
        BarraNavegacion.setBackground(color);
    }

    public void colorBarraT(Color color) {
        BarraTareas.setBackground(color);
    }

    public void colorFondoP(Color color) {
        FondoPantalla.setBackground(color);
    }

    public void ocultarEdicionPantalla(boolean mostrar) {
//        editor.setVisible(mostrar);
//        editorElementos.setVisible(mostrar);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Principal().setVisible(true));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraNavegacion;
    private javax.swing.JPanel BarraTareas;
    private javax.swing.JPanel FondoPantalla;
    private javax.swing.JMenu ModificarPantalla;
    private javax.swing.JButton WitZig;
    private javax.swing.JButton editorTexto1;
    private javax.swing.JButton explorarArchivos;
    private javax.swing.JLabel fondoImagen;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
